version: '3'
services:
  server:
    build: ./server
    container_name: BIKE_FORCE-server
    command: npm run start
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - DB_NAME=BIKE_FORCE
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=server_db
      - DB_PORT=5432
      - JWT_ACCESS_SECRET=437FvlrIM833F9SvwCE5
      - JWT_REFRESH_SECRET=rfme737gsHDhfu48Yhd7
      - CLIENT_URL_ADMINPANEL=http://localhost:3000
      - CLIENT_URL_MARKET=http://localhost:8080
      - ADMIN_PASSWORD=12345678
      - ADMIN_EMAIL=admin@mail.ru
    depends_on:
      - server_db
      - pgadmin
    networks:
      - BIKE_FORCE-network
    volumes:
      - server-data:/usr/src/app/static

  server_db:
    image: postgres:15
    container_name: BIKE_FORCE-server_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=BIKE_FORCE
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - BIKE_FORCE-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: BIKE_FORCE-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - server_db
    networks:
      - BIKE_FORCE-network

  # убедиться что порт 80 свободен!
  # nginx:
  #   image: nginx:stable
  #   container_name: BIKE_FORCE-nginx
  #   ports:
  #    - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
  #   depends_on:
  #     - frontend
  #     - server
  #     - auth

volumes:
  postgres-data:
  pgadmin_data:
  server-data:

networks:
  BIKE_FORCE-network:
    driver: bridge
# docker-compose up --build
# docker exec -t NAME_CONTAINER sh
